version: "3.3"

services:
  db:
    container_name: dbcourses
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  api:
    container_name: apicourses
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/db
      MICROSERVICES: ${MICROSERVICES}
    ports:
      - "8000:8000"
    depends_on:
      - db